name: Website (ticket) - Production
on:
  push:
    branches:
      - production
jobs:
  build:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/production
          fetch-depth: 1

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0

      - name: 'Configure docker for artifact registry'
        shell: bash
        run: |
          gcloud auth configure-docker ${{ inputs.registry }}

      - id: docker-build
        shell: bash
        run: |
          docker build . -t user-${{ github.run_id }}-${{ github.run_attempt }} --platform linux/amd64

      - name: 'Push docker'
        shell: bash
        run: |
          docker push user-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Deploy a Cloud Run service
        id: deploy-service
        uses: google-github-actions/deploy-cloudrun@v0.1.0
        with:
          image: user-${{ github.run_id }}-${{ github.run_attempt }}
          service: user