name: Backend user - Production

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-east1-docker.pkg.dev/douter/backend/user:${{ github.sha }}
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Login GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0
    
    - name: Configure Docker
      run: gcloud auth configure-docker asia-east1-docker.pkg.dev
    
    - name: Build Docker image
      run: docker build . -t $IMAGE_NAME
    
#    - name: Test Docker image
#      run: docker run $IMAGE_NAME sh -c "yarn run test"
    
    - name: Push Docker image
      run: docker push $IMAGE_NAME
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        image: ${{ env.IMAGE_NAME }}
        service: backend-user-service
#    - name: Deploy Docker image
#      run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed