name: Backend (user) - Production

on:
  push:
    branches: production

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
        with:
          ref: refs/heads/production
          fetch-depth: 1

      - name: 'Auth GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0

      - name: 'Configure docker for artifact registry'
        shell: bash
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY }}

      - id: docker-build
        shell: bash
        run: |
          docker build . -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}/user:${{ github.sha }} --platform linux/amd64

      - name: 'Push docker'
        shell: bash
        run: |
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}/user:${{ github.sha }}

  deploy:
    needs: use-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy a Cloud Run service
        id: deploy-service
        uses: google-github-actions/deploy-cloudrun@v0.1.0
        with:
          image: ${{ secrets.GCP_ARTIFACT_REGISTRY }}/user:${{ github.sha }}
          service: user